server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-current-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_book
    username: postgres
    password: root@123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:postgresql://localhost:5432/db_book
    user: postgres
    password: root@123
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    config-url: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs